// Textes de l'interface. Le fon utilise l'interface française (pas encore de traduction validée).
const FR = {
    title: "Assistant SSR",
    subtitle: "Santé sexuelle & reproductive · confidentiel",
    close: "Fermer",
    newChat: "Nouvelle conversation",
    hello: "Bonjour, je suis là pour toi",
    intro: "Pose-moi tes questions sur la santé sexuelle et reproductive. C'est anonyme, sans jugement.",
    suggestions: [
        "Comment bien utiliser un préservatif ?",
        "Mes règles sont en retard, que faire ?",
        "Quelles méthodes de contraception existent ?",
        "Où trouver des kits gratuits ?",
    ],
    placeholder: "Pose ta question…",
    send: "Envoyer",
    stop: "Arrêter",
    thinking: "L'IA réfléchit",
    disclaimer: "Informations générales : ne remplace pas une consultation.",
    sources: "Sources",
    fonNotice: "La version fon n'est pas encore disponible pour cette réponse : elle est donnée en français.",
    stopped: "Réponse interrompue.",
    retry: "Réessayer",
    expertTitle: "Parler à un expert SSR",
    expertText: "Rendez-vous privé et confidentiel avec un conseiller Edotofamily.",
    expertCta: "Prendre rendez-vous",
    emergencyTitle: "Tu n'es pas seul·e",
    emergencyContacts: "Contacts d'urgence",
    products: "Produits disponibles",
    see: "Voir",
    campaigns: "Kits gratuits près de toi",
    seeCampaigns: "Voir les campagnes",
    langBeta: "bêta",
};

const EN = {
    ...FR,
    subtitle: "Sexual & reproductive health · confidential",
    close: "Close",
    newChat: "New conversation",
    hello: "Hi, I'm here for you",
    intro: "Ask me anything about sexual and reproductive health. It's anonymous and judgement-free.",
    suggestions: [
        "How do I use a condom correctly?",
        "My period is late, what should I do?",
        "What contraception methods exist?",
        "Where can I get free kits?",
    ],
    placeholder: "Ask your question…",
    send: "Send",
    stop: "Stop",
    thinking: "Thinking",
    disclaimer: "General information only: not a substitute for a consultation.",
    sources: "Sources",
    stopped: "Response stopped.",
    retry: "Retry",
    expertTitle: "Talk to an SRH expert",
    expertText: "Private, confidential appointment with an Edotofamily counsellor.",
    expertCta: "Book an appointment",
    emergencyTitle: "You are not alone",
    emergencyContacts: "Emergency contacts",
    products: "Available products",
    see: "View",
    campaigns: "Free kits near you",
    seeCampaigns: "See campaigns",
    langBeta: "beta",
};

export const chatStrings = (lang) => (lang === "en" ? EN : FR);
